---
title: "software_comp_preprocess"
author: "Luis Daniel Chavarría"
date: "27/12/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data viz software comparison pre processing

The purpose of this script is to prepare the data from the data analytics diplomat in order to create a useful standardized visualization.

```{r}
library(plyr)
library(tidyverse)
library(readxl)
library(plotly)


raw_data <- read_excel("../../database/Datos.xlsx")

colnames(raw_data) <- c("atencion", "id", "nombre", "fechanac", "edad",
                     "genero", "tel", "dir", "grupob", "etnia",
                     "niveledu", "cronico", "segcronico", "eps",
                     "fechaing", "horaing", "diaseming", "anoing", "mesing", "diaing","urg", "tipurg", 
                     "espurg", "dxurg","inter", "espinter", "codxpri", 
                     "esturg", "estb1","estb3", "estuce", "estuci", "estotal",
                     "cirugia","dxpreq", "ordurg", "proc","pisodes", 
                     "esp","tiempoq", "quirofano")

glimpse(raw_data)
```

# Let's use the diplomate's basic data cleaning to make things faster

```{r}

clean_diplomate <- raw_data %>% 
  mutate(atencion = as.character(atencion),
         id = as.character(id),
         nombre = as.character(nombre),
         edad = as.numeric(edad),
         genero = as_factor(genero),
         cronico = as_factor(cronico),
         segcronico = as_factor(segcronico),
         eps = as_factor(eps),
         urg = as_factor(urg),
         tipurg = as_factor(tipurg),
         inter = as_factor(inter),
         ordurg = as_factor(ordurg),
         cirugia = as_factor(cirugia),
         proc = as_factor(proc),
         pisodes = as_factor(pisodes),
         esp = as_factor(esp)
         ) %>% 
  filter(edad < 110)

levels(clean_diplomate$cronico) <- c("No", NA, "Sí")
clean_diplomate$segcronico <- revalue(clean_diplomate$segcronico, c("SD" = NA))
clean_diplomate$tipurg <- revalue(clean_diplomate$tipurg, 
                        c("N/A"="No aplica"))
clean_diplomate$ordurg <- revalue(clean_diplomate$ordurg, c("ELECTIVO"="Electivo", 
                                        "N/A"="No aplica",
                                        "URGENTE"="Urgente"))
clean_diplomate$proc <- revalue(clean_diplomate$proc, c("N/A"="No aplica"))
clean_diplomate$pisodes <- revalue(clean_diplomate$pisodes, c("N/A"="No aplica"))

clean_diplomate %>% 
  summary()
glimpse(clean_diplomate)

# clean_diplomate %>% 
#   write_excel_csv2("../../database/clean_diplomate.csv")
```

```{r}
segcronico_pareto <- clean_diplomate %>% 
  count(segcronico, sort = T) %>% 
  mutate(cumulative = cumsum(n),
         perc = (cumulative/sum(n))) %>% 
  na.omit()

# segcronico_pareto %>%
#   write_excel_csv2("../../database/segcronico_pareto.csv")
```

# Standard plot to replicate in each software


```{r}
scale_right <- tail(segcronico_pareto$perc, n=1)/tail(segcronico_pareto$cumulative, n=1)

segcronico_pareto %>%
  ggplot(aes(x = reorder(segcronico, -n))) +
  geom_bar(aes(y = segcronico_pareto$n), stat = "identity", fill = "deepskyblue4") +
  geom_point(aes(y = cumulative, group = 1), size = 2) +
  geom_path(aes(y = cumulative, group = 1), size = 0.9) +
  geom_hline(yintercept = 72116, color = "red") +
  scale_y_continuous(sec.axis = sec_axis(~.*scale_right/100, name = "Porcentaje acumulado (%)", labels = scales::percent_format())) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 75, vjust = 0.6)) +
  labs(title = "Pareto de Segmentos crónicos", subtitle = "Desarrollo Organizacional", x = 'Segmentos crónicos', y = "Pacientes")

ggsave("../visualization/pareto_r.png", width = 30, height = 18, units = "cm")

```


